stages:
  - build
  - test
  - deploy
  - cleanup

# Use Anchors to simplify YAML when GitLab is further upgraded

build_linux_py2:
  stage: build
  script:
    - export PATH=$MY_CONDA_PATH:$PATH
    - conda env create -q -n quest-py2-$CI_BUILD_REF -f py2_conda_environment.yml
    - source activate quest-py2-$CI_BUILD_REF
    - python setup.py install
    - source deactivate
  tags:
    - linux

build_linux_py3:
  stage: build
  script:
    - export PATH=$MY_CONDA_PATH:$PATH
    - echo $PATH
    - conda env create -q -n quest-py3-$CI_BUILD_REF -f py3_conda_environment.yml
    - source activate quest-py3-$CI_BUILD_REF
    - python setup.py install
    - source deactivate
  tags:
    - linux
    
build_mac_py2:
  stage: build
  script:
    - export PATH=$MY_CONDA_PATH:$PATH
    - conda env create -q -n quest-py2-$CI_BUILD_REF -f py2_conda_environment.yml
    - source activate quest-py2-$CI_BUILD_REF
    - python setup.py install
    - source deactivate
  tags:
    - mac

build_mac_py3:
  stage: build
  script:
    - export PATH=$MY_CONDA_PATH:$PATH
    - echo $PATH
    - conda env create -q -n quest-py3-$CI_BUILD_REF -f py3_conda_environment.yml
    - source activate quest-py3-$CI_BUILD_REF
    - python setup.py install
    - source deactivate
  tags:
    - mac
    
build_win_py2:
  stage: build
  script:
    - echo %MY_CONDA_PATH%
    - call set PATH=%MY_CONDA_PATH%\..;%MY_CONDA_PATH%;%PATH%
    - call conda env create -q -n quest-py2-%CI_BUILD_REF% -f py2_conda_environment.yml
    - call activate quest-py2-%CI_BUILD_REF%
    - python setup.py install
    - call deactivate
  tags:
    - win

build_win_py3:
  stage: build
  script:
    - echo %MY_CONDA_PATH%
    - call set PATH=%MY_CONDA_PATH%\..;%MY_CONDA_PATH%;%PATH%
    - call conda env create -q -n quest-py3-%CI_BUILD_REF% -f py3_conda_environment.yml
    - call activate quest-py3-%CI_BUILD_REF%
    - python setup.py install
    - call deactivate
  tags:
    - win

test_linux_py2:
  stage: test
  script:
    - echo $MY_CONDA_PATH
    - export PATH=$MY_CONDA_PATH:$PATH
    - source activate quest-py2-$CI_BUILD_REF
    - py.test test
    - source deactivate
  tags:
    - linux

test_linux_py3:
  stage: test
  script:
    - export PATH=$MY_CONDA_PATH:$PATH
    - source activate quest-py3-$CI_BUILD_REF
    - py.test test
    - source deactivate
  tags:
    - linux

test_mac_py2:
  stage: test
  script:
    - echo $MY_CONDA_PATH
    - export PATH=$MY_CONDA_PATH:$PATH
    - source activate quest-py2-$CI_BUILD_REF
    - py.test test
    - source deactivate
  tags:
    - mac

test_mac_py3:
  stage: test
  script:
    - export PATH=$MY_CONDA_PATH:$PATH
    - source activate quest-py3-$CI_BUILD_REF
    - py.test test
    - source deactivate
  tags:
    - mac

test_win_py2:
  stage: test
  script:
    - call set PATH=%MY_CONDA_PATH%\..;%MY_CONDA_PATH%;%PATH%
    - call activate quest-py2-%CI_BUILD_REF%
    - call py.test test
    - call deactivate
  tags:
    - win

test_win_py3:
  stage: test
  script:
    - call set PATH=%MY_CONDA_PATH%\..;%MY_CONDA_PATH%;%PATH%
    - call activate quest-py3-%CI_BUILD_REF%
    - call py.test test
    - call deactivate
  tags:
    - win

docs:
  stage: deploy
  only:
    - master
  script:
    - source $MY_CONDA_PATH/activate quest-py3-$CI_BUILD_REF
    - conda install sphinx
    - make -C docs html
    - tar -czf documentation.tar.gz docs/_build/html
    - source deactivate
# Artifacts will be available yet after further GitLab upgrade
#  artifacts:
#    paths:
#    - documentation.tar.gz
  tags:
    - docs

cleanup_linux_job:
  stage: cleanup
  script:
    - $MY_CONDA_PATH/conda env remove -q -y -n quest-py2-$CI_BUILD_REF
    - $MY_CONDA_PATH/conda env remove -q -y -n quest-py3-$CI_BUILD_REF
# 'When' parameter will be available yet after further GitLab upgrade
#  when: always
  tags:
    - linux

cleanup_mac_job:
  stage: cleanup
  script:
    - $MY_CONDA_PATH/conda env remove -q -y -n quest-py2-$CI_BUILD_REF
    - $MY_CONDA_PATH/conda env remove -q -y -n quest-py3-$CI_BUILD_REF
# 'When' parameter will be available yet after further GitLab upgrade
#  when: always
  tags:
    - mac

cleanup_win_job:
  stage: cleanup
  script:
    - call %MY_CONDA_PATH%\conda env remove -q -y -n quest-py2-%CI_BUILD_REF%
    - call %MY_CONDA_PATH%\conda env remove -q -y -n quest-py3-%CI_BUILD_REF%
# 'When' parameter will be available yet after further GitLab upgrade
#  when: always
  tags:
    - win