# conda environment file for python 3, includes packages needed for testing
# create a conda virtual env using:
#   conda env create -n myenv --file py3_conda_environment.yml
#   source activate myenv (use 'activate myenv' on windows)
#   python setup.py develop
#
# optionally run tests:
#   python setup.py test

name: quest

channels:
    - conda-forge
    - defaults

dependencies:
    - python=3
    - fiona
    - rasterio
    - gdal
    - numpy
    - geojson
    - jinja2
    - json-rpc
    - ulmo>=0.8.3.2
    - pyyaml
    - matplotlib
    - click
    - werkzeug
    - peewee
    - stevedore
    - geopandas
    - distributed
    - psutil
    - pint
    - pony
    - tornado
    - pymongo
